#nelmio_cors:
#    defaults:
#        origin_regex: true
#        allow_origin: ['^http://sf.test:[0-9]+']
#        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'TRACE', 'HEAD']
#        allow_headers: ['*']
#        expose_headers: []
#        max_age: 3600
